---
title: "A.2. Distribution Year of Birth by Country"
description: Birthyear distribution by country and legacy
---

Directories:
```{r}
source("source_file.R")
```

Import data:
```{r}
df = read.csv(paste0(data_dir, "wvs-merged.csv"))
agg = read.csv(paste0(data_dir, "authors-country_data.csv"))
```

`function` to create density dataframe for country **i**
```{r}
density_frame = function(cntry) {
 data = data.frame(
  country = as.character(cntry),
  year = with(density(df$birth[df$country==cntry]), data.frame(x, y))[,1],
  density = with(density(df$birth[df$country==cntry]), data.frame(x, y))[,2],
  start = mean(df$startyear[df$country==cntry]),
  end = mean(df$endyear[df$country==cntry]), 
  legacy = subset(df, country == cntry)$legacy[1], 
  N = length(subset(df, country == cntry)$legacy))
 
 return(data)
}
```

Create density distribution by country and bind in one dataframe:
```{r}
density = list()

for (i in c(1:length(unique(df$country)))) {
 cntry = unique(df$country)[i]
 density[[i]] = density_frame(cntry)
}

density = do.call(rbind, density)
density$sampsize = paste0(density$country, " (N = ", density$N, ")")
```

Plot density function by country:
```{r}
library(ggridges)
library(ggplot2)

ggplot(data = density, mapping = aes(x = year, y = density)) +
 geom_area(fill = "white", alpha = 0, color = "grey20") + 
 geom_area(data = subset(density, legacy !="Democratic"), 
  mapping = aes(x = ifelse(year>start & year< end , year, 0), fill = legacy), alpha = 0.5) +
 geom_text(data = agg, aes(x = startyear, y = 0, label = startyear), vjust = -0.4, hjust = 1, size = 3) +
 geom_text(data = agg, aes(x = endyear, y = 0, label = endyear), vjust = -0.4, hjust = 0, size = 3) +
 geom_point(data = agg, aes(x = endyear, y = 0)) + geom_point(data = agg, aes(x = startyear, y = 0)) +
 scale_x_continuous(minor_breaks = FALSE, limits = c(1890, 2010)) +
 scale_fill_manual(values = c("grey20", "grey60"), labels = c("Left-Wing", "Right-Wing")) +
 facet_wrap(sampsize ~ ., ncol = 5) +
 theme_minimal() + 
 theme(axis.title = element_blank(), axis.ticks.y = element_blank(), 
       axis.text = element_blank(), legend.position = "bottom", legend.title = element_blank())

ggsave(paste0(out_dir, "test.png"), width = 8, height = 12)
```

    
     
    
    
    
    
    
