---
title: "A.4. Correlates of the Left-Right Dimension"
---

Directories:
```{r}
source("source_file.R")
```

Import data:
```{r}
df = read.csv(paste0(data_dir, "wvs-merged.csv"))
agg = read.csv(paste0(data_dir, "authors-country_data.csv"))
```

`function` to calculate country-clustered correlations:
```{r}
corr_frame = function(variable) {
 library(ggpubr)
 df$leg_no = as.numeric(factor(df$legacy))
 corrlist = list()
 
 for (i in c(1:3)) { # start legacy loop
  legacy = subset(df, leg_no == i) # subset legacy
  
  legacy$country_no = as.numeric(factor(legacy$country)) # numeric country vector for loop
  countrycorrs = list() # empty list to store counrtry correlations 
  
  for (j in c(1:length(unique(legacy$country_no)))) { # start country loop
   country = subset(legacy, country_no == j) # subset country
   var = subset(country, select = c(variable))[,1] # select variable
   
   if (length(var[!is.na(var)] > 1)) { # if country has observations ...
    correlation = cor.test(var, country$lrscale, method = "pearson") # ... calculate correlation
    countrycorrs[[j]] = data.frame(
     lb = c(correlation[[9]])[1], ub = c(correlation[[9]])[2], corr = c(correlation[[4]]))} 
  } # end country loop
  
  countrycorrs = data.frame(do.call(rbind, countrycorrs))
  countrycorrs = lapply(countrycorrs, mean)
  corrlist[[i]] = data.frame(countrycorrs)
  
 } # end legacy loop
 
 corrlist = data.frame(do.call(rbind, corrlist))
 corrlist$legacy = c("Democratic", "Left-Authoritarian", "Right-Authoritarian")
 
 return(corrlist)
}
``` 
 
Dataframe of correlations:
```{r}
corrs = data.frame(rbind(
 cbind(var = "Democratic Support", corr_frame("autdem")), 
 cbind(var = "Nationalism", corr_frame("nat")), 
 cbind(var = "Social Policy", corr_frame("socpol")), 
 cbind(var = "Income Inequality", corr_frame("inceq")), 
 cbind(var = "Liberalism", corr_frame("lib")), 
 cbind(var = "Gender Equality", corr_frame("equality")) 
 ))
```

```{r}
corrs$var2 = as.numeric(corrs$var)
vsp = 0.15

ggplot2::ggplot(data = corrs, aes(x = corr, y = var2, color = legacy)) +
 geom_vline(xintercept = 0, size = 0.5, color = "grey50") +
 geom_segment(data = subset(corrs, legacy == "Democratic"), aes(x=lb, xend=ub, y=var2, yend=var2)) + 
 geom_segment(data = subset(corrs, legacy == "Left-Authoritarian"), 
              aes(x=lb, xend=ub, y=var2-vsp, yend=var2-vsp)) +
 geom_segment(data = subset(corrs, legacy == "Right-Authoritarian"), 
              aes(x=lb, xend=ub, y=var2+vsp, yend=var2+vsp))+
 geom_point(data = subset(corrs, legacy == "Democratic"), aes(x=corr,y=var2)) +
 geom_point(data = subset(corrs, legacy == "Left-Authoritarian"), aes(x=corr,y=var2-vsp)) +
 geom_point(data = subset(corrs, legacy == "Right-Authoritarian"), aes(x=corr,y=var2+vsp)) +
 scale_y_continuous(breaks = seq(1,6,1), labels = unique(corrs$var)) + 
 scale_color_manual(values = c("grey20","grey50", "grey80")) +
 theme_minimal() + xlab("Country-Clustered Correlation with Left-Right Orientation") +
 theme(axis.title.y = element_blank(), legend.title = element_blank(), panel.grid.minor = element_blank(),
       axis.title.x = element_text(size = 8, vjust = -0.1)) 

ggsave(paste0(out_dir, "annex_lrcorrs.png"), width = 6, height = 3)
```
