---
title: "Data Preparation - VDem Regime Characteristics"
---

```{r}
vdem = read.csv(paste0(data_dir, "vdem-country_year.csv"))
```

Subset the regime years: 
```{r}
vdem_autyears = list()

vdem_sub = subset(vdem, legacy!="Democratic")

for (i in c(1:length(unique(vdem_sub$country)))) {
 country = subset(vdem_sub, country == unique(vdem_sub$country)[i])
 autvec = c(country$startyear[1]: country$endyear[1])  
 for (j in c(1:length(autvec))) {
   value = autvec[j]
   country$keep[country$year == value] = 1
 }
 vdem_autyears[[i]] = subset(country, keep == 1) # subset years of authoritarianism 
}

vdem_autyears = data.frame(do.call(rbind, vdem_autyears))
```

Aggregate 
```{r}
vdem_agg = data.frame(
 country = aggregate(indoctrination ~ country, data = vdem_autyears, FUN = mean)[,1],
 indoc_mean = aggregate(indoctrination ~ country, data = vdem_autyears, FUN = mean)[,2],
 repr_mean = aggregate(repression ~ country, data = vdem_autyears, FUN = mean)[,2],
 indoc_max = aggregate(indoctrination ~ country, data = vdem_autyears, FUN = mean)[,2],
 repr_max = aggregate(repression ~ country, data = vdem_autyears, FUN = mean)[,2])

vdem_agg$country = as.character(vdem_agg$country)
```

```{r}
rescale = function(x) {
 x = x - min(x, na.rm = TRUE)
 x = x / max(x, na.rm = TRUE)
 return(x)
}
```

```{r}
vdem_agg$indoctrination_r = (rescale(vdem_agg$indoc_mean)*-1)+1
vdem_agg$repression_r = (rescale(vdem_agg$repr_mean)*-1)+1
```

```{r}
write.csv(vdem_agg, paste0(out_dir, "vdem-regime_characteristics.csv"))
```



