---
title: "A.3. Democratic Support and Ideological Extremism"
---

Directories:
```{r}
source("source_file.R")
```

Import data:
```{r}
df = read.csv(paste0(data_dir, "wvs-merged.csv"))
agg = read.csv(paste0(data_dir, "authors-country_data.csv"))
```

Categorical variable democratic support and left-right orientation
```{r}
# Democratic support
df$autdem_cat = NA
df$autdem_cat[df$autdem<0] = 1 # antidemocratic
df$autdem_cat[df$autdem==0] = 2 # neutral
df$autdem_cat[df$autdem>0] = 3 # prodemocratic

# Left-right orientation
df$lrcat = NA
df$lrcat[df$lrscale <= 2] = 1 # extreme left
df$lrcat[df$lrscale > 2 & df$lrscale < 5] = 2 # center left
df$lrcat[df$lrscale == 5] = 3 # center
df$lrcat[df$lrscale > 5 & df$lrscale < 8] = 4 # center right
df$lrcat[df$lrscale >= 8] = 5 # extreme right
```

```{r}
lrdist = function(legacy_chr) {
 data = subset(df, legacy == legacy_chr & !is.na(lrcat) & !is.na(autdem_cat))
 out = data.frame(cbind(
             legacy = legacy_chr, 
             n_sub = data.frame(table(data$lrcat, data$autdem_cat))[,3],
             ideology = data.frame(prop.table(table(data$lrcat, data$autdem_cat), 2))[,1],
             type = data.frame(prop.table(table(data$lrcat, data$autdem_cat),2))[,2],
             proportion = data.frame(prop.table(table(data$lrcat, data$autdem_cat),2))[,3]))
 
 out$proportion = as.numeric(as.character(out$proportion))
 out$n_sub = as.numeric(as.character(out$n_sub))
 
 out$type = factor(out$type, levels = c(1:3), labels = c("Antidemocratic", "Indifferent", "Prodemocratic"))
 out$ideology = factor(out$ideology, levels = c(1:5), 
                       labels = c("Extreme Left", "Center Left", "Center", "Center Right", "Extreme Right"))
 
 return(out)
}

lr_dist = rbind(lrdist("Left-Wing"), lrdist("Democratic"), lrdist("Right-Wing"))
lr_dist_agg = aggregate(df$country, by=list(df$legacy), FUN=length)
colnames(lr_dist_agg) = c("legacy", "n_total")
lr_dist = merge(lr_dist, lr_dist_agg, by = c("legacy"))
lr_dist$SE = sqrt((lr_dist$n_sub / lr_dist$n_total)*(1-(lr_dist$n_sub / lr_dist$n_total))/lr_dist$n_total) 
lr_dist$error = qnorm(.975)*lr_dist$SE
```

```{r}
library(ggplot2)

ggplot(data = subset(lr_dist, ideology == "Extreme Left" | ideology == "Extreme Right"), 
       aes(x = legacy, y = proportion, fill = type)) + 
 geom_col(position = "dodge", color = "black", alpha = 0.5, size = 0.1) + 
 geom_errorbar(aes(ymin=proportion-error, ymax=proportion+error), 
               width=.25, size = 0.3, position=position_dodge(.9)) +
 theme_minimal() + 
 theme(axis.text.x = element_text(angle = 90), axis.title = element_blank(),
       legend.position = "bottom", legend.title = element_blank()) + 
 scale_fill_manual(values = c("grey20", "grey50", "grey80")) +
 facet_grid(.~ ideology) + 
 coord_cartesian(ylim=c(0.05,0.20)) 
 
ggsave(paste0(out_dir, "annex_autdemextremes.png"), width = 9, height = 5.5)
```