---
title: "C.1. Country-Level Legacy Effects"
---

Directories:
```{r}
source("source_file.R")
```

```{r}
germany = subset(df, country == "West Germany" | country == "East Germany")
germany$country = factor(germany$country)
gam_germany = mgcv::gam(autdem ~ s(lrscale, k = 10, by = country), data = germany)

library(ggplot2)
ggplot(subset(df, country == "Hungary" | country == "East Germany" | country == "West Germany"), aes(x = lrscale, y = autdem, color = country)) + 
  geom_smooth()
```


Import data:
```{r}
agg = read.csv(paste0(data_dir, "authors-country_data.csv"))
agg = subset(agg, legacy != "Democratic")

df = read.csv(paste0(data_dir, "wvs-merged.csv"))
df$native = factor(df$native); df$relig = factor(df$relig); df$educ = factor(df$educ); df$gndr = factor(df$gndr); df$exposure_age = factor(df$exposure_age); df$age_cat = factor(df$age_cat)
head(df)
```

Base plot:
```{r}
base = function(var) {
 library(ggplot2)
 plot = ggplot(data = agg, aes(x = var, y = prox, label = country)) + 
 geom_hline(yintercept = 0, size = 0.2) +
 geom_point () + geom_smooth(method = "lm", color = "black", size = 0.5) + 
 geom_text(size = 2, hjust = -0.25) + 
 labs(y=expression(italic("r")~'(Ideological Proximity, Democratic Support)')) +
 theme_minimal() + theme(axis.title.x = element_blank())
 
 return(plot)
}
```

Plots: 
```{r}
base(agg$duration) # regime duration
ggsave(paste0(robust_dir, "countrylegacy-duration.png"))
base(agg$indoctrination_r) # regime indoctrination
ggsave(paste0(robust_dir, "countrylegacy-indoctrination.png"))
base(agg$repression_r) # regime repression
ggsave(paste0(robust_dir, "countrylegacy-repression.png"))
```

Distance of Experience:
```{r}
datasets = list(subset(df, legacy == "Right-Wing"), subset(df, legacy == "Left-Wing"))
longev_list = list()

for (i in c(1:2)) {
 library(lme4); library(lmerTest)
 longev_list[[i]] = lmer(
  autdem ~ lrscale + year + year*lrscale + (1 | country),
  data = datasets[[i]])
}
```

```{r}
longev_list = data.frame(
 legacy = c(rep("Right-Wing", 5), rep("Left-Wing", 5)),
 param = rep(c("Left-Right", "Year 1999", "Year 2008", "Left-Right: 1999", "Left-Right: 2008"), 2),
 coeff = c(-0.069, 0.086,-0.024, 0.013, 0.026, 0.038, -0.001, 0.019, 0.032,-0.009),
 se = c(0.017, 0.069, 0.069, 0.012, 0.012, 0.003, 0.031, 0.029, 0.005, 0.005))
```


```{r}
ggplot2::ggplot(data = longev_list, aes(x = param, y = coeff)) + 
 geom_point() + geom_hline(yintercept = 0, size = 0.2, color = "grey40") +
 geom_errorbar(mapping = aes(ymin = coeff - se, ymax = coeff + se), size = 0.2, width = 0.2) + 
 coord_flip() + theme_minimal() + theme(axis.title = element_blank()) +
 facet_grid(.~legacy)

ggsave(paste0(robust_dir, "countrylegacy-distance.png"), width = 6, height = 3)
```

