---
title: "B.3. Analysis by Country"
---

Directories:
```{r}
source("source_file.R")
```

Import data:
```{r}
df = read.csv(paste0(data_dir, "wvs-merged.csv"))
df$native = factor(df$native); df$relig = factor(df$relig); df$educ = factor(df$educ); df$gndr = factor(df$gndr); df$exposure_age = factor(df$exposure_age); df$age_cat = factor(df$age_cat)
```

Hypothesis 1:
```{r}
for (i in c(1:length(unique(df$country)))) {
 cntry = unique(df$country)[i]
 directory = paste0(robust_dir, "bycountry-h1_", cntry, ".txt")
 data = subset(df, country == cntry)
 model = lm(autdem ~ lrscale, data = data)
 sink(directory); print(summary(model)); sink()  
}
```

Hypothesis 2a:
```{r}
df = subset(df, legacy != "Democratic")

for (i in c(1:length(unique(df$country)))) {
 cntry = unique(df$country)[i]
 directory = paste0(robust_dir, "bycountry-h2a_", cntry, ".txt")
 data = subset(df, country == cntry)
 model = lm(autdem ~ lrscale + exp + lrscale*exp, data = data)
 sink(directory); print(summary(model)); sink()  
}
```

Hypothesis 2b:
```{r}
for (i in c(1:length(unique(subset(df, legacy!="Democratic")$country)))) {
 cntry = unique(subset(df, legacy!="Democratic")$country)[i]
 directory = paste0(robust_dir, "bycountry-h2b_", cntry, ".txt")
 data = subset(df, country == cntry)
 model = lm(autdem ~ lrscale + exposure + lrscale*exposure, data = data)
 sink(directory); print(summary(model)); sink()  
}
```

Hypothesis 2c
```{r}
for (i in c(1:length(unique(df$country)))) {
 cntry = unique(df$country)[i]
 directory = paste0(robust_dir, "bycountry-h2c_", cntry, ".txt")
 data = subset(df, country == cntry)
 model = lm(autdem ~ lrscale + exposure_age + exposure_age*lrscale, data = data)
 sink(directory); print(summary(model)); sink()  
}
```
