---
title: "Figure 2 - Country Legacy Effects"
---

Libraries: 
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
lapply(c("mgcv", "gamm4", "rstanarm", "ggpubr", "ggplot2", "plyr", "dplyr", "tidymv", "ggrepel"), 
       require, character.only = TRUE)
```

Import data:
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
source("source_file.R")
df = subset(df, country != "Hungary" & country != "East Germany")
```

Generalized Additive Model without random effects for each country:
```{r}
h1_gams = list()
h1_gams_pred = list()

for (i in c(1:3)) {
 legacydata = subset(df, legacy == unique(df$legacy)[i])
 h1_gams[[i]] = gam(autdem ~ s(lrscale, k = 10), data = legacydata)
 h1_gams_pred[[i]] = tidymv::predict_gam(h1_gams[[i]])
 h1_gams_pred[[i]]$legacy = unique(df$legacy)[i]
 capture.output(summary(h1_gams[[i]]), 
                file = paste0(tab_dir, "h1_", unique(df$legacy)[i], ".txt"))
}

h1_gams_pred = do.call(rbind, h1_gams_pred)
```

Random effects per country:
```{r}
h1_re_pred = list()
for (i in c(1:length(unique(df$country)))) {
 gam = gam(autdem ~ s(lrscale, k = 10), data = subset(df, country == unique(df$country)[i]))
 h1_re_pred[[i]] = tidymv::predict_gam(gam)
 h1_re_pred[[i]]$country = unique(df$country)[i]
}

h1_re_pred = do.call(rbind, h1_re_pred)
legacies = subset(country_data, select = c("country", "legacy"))
h1_re_pred = merge(h1_re_pred, legacies, by = "country", all = TRUE)
```

Table containing distribution of respondents across the left-right dimension per legacy:
```{r}
tab = data.frame(prop.table(table(df$lrscale, df$legacy),margin = 2))
colnames(tab) = c("lrscale", "legacy", "proportion")
tab$lrscale = as.numeric(as.character(tab$lrscale))
```

Effective Degrees of Freedom Statistics:
```{r}
edfs = data.frame(
 legacy = c("Left-Wing", "Right-Wing", "Democratic"),
 edf = c(7.817, 8.054, 8.733),
 sign = c("***", "***", "***"),
 lrscale = rep(9,3),
 fit = rep(2.5,3)
)
```

```{r}
ggplot(h1_gams_pred, aes(lrscale, fit)) + 
 geom_smooth(data = h1_re_pred, aes(lrscale, fit, group = country), 
             se = FALSE, color = "grey90", size = 0.2, alpha = 0.5) + 
 geom_smooth_ci() + 
 geom_hline(yintercept = 0) + 
 geom_histogram(data = tab, aes(x = lrscale, y = proportion), stat = "identity", alpha = 0.6) + 
 geom_label_repel(data = edfs, 
                  aes(lrscale, fit, label = paste0("edf %~~%", "italic('", edf, "')")), parse = TRUE,
                  point.padding = NA) + 
 xlab("Left-Right Orientation") + ylab("Democratic Support") + 
 scale_x_continuous(breaks = c(1:10)) + 
 scale_y_continuous(breaks = seq(-0.5,2.5,0.5),limits = c(0, 2.5)) + 
 facet_grid(.~ legacy) + 
 theme_minimal() + 
 theme(strip.text = element_text(face = "bold", vjust = 3, size = 11),
       panel.grid.minor = element_blank(),
       axis.title = element_text(size = 10))

dev.copy(png,paste0(fig_dir, 'Figure 2 - Country Legacy Effects.png'), width = 3000, height = 2000, res=400)
dev.off()
```


