---
title: "Table 3 - Individual Level Legacy Effects"
---

Import Libraries:
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(lme4)
library(lmerTest)
library(boot)
library(lm.beta)
library(memisc)
library(plyr)
```

Import Data:
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
source("source_file.R")
df = subset(df, country != "Hungary" & country != "East Germany")
df$country = factor(df$country)
```

Rescale left-right:
```{r}
df$age = scales::rescale(df$age, c(0:1))
df$lrscale = scales::rescale(df$lrscale, c(0,1))
df$educ = scales::rescale(as.numeric(plyr::revalue(factor(df$educ), c(
        "Uncompleted Primary" = "1",
        "Completed Primary" = "2", 
        "Uncompleted Secondary Vocational" = "3",
        "Completed Secondary Vocational" = "4",
        "Uncompleted Secondary Academic" = "5",
        "Completed Secondary Academic" = "6",
        "University without Official Degree" = "7", 
        "University with Official Degree" = "8"
        ))), c(0,1))
df$polint = scales::rescale(df$polint, c(0,1))
df$autdem2 = scales::rescale(df$autdem, c(0,1))
```

```{r}
h2_models = list()

h2_models[[1]] = lmer(
  autdem ~ lrscale + exp + lrscale*exp + age + educ + polint + sex + survey + (1 | country), 
  data = subset(df, legacy == unique(df$legacy)[1])) # Left-Wing
h2_models[[2]] = lmer(
  lrscale ~ autdem2 + exp + autdem2*exp + age + educ + polint + sex + survey + (1 | country), 
  data = subset(df, legacy == unique(df$legacy)[1])) # Left-Wing

h2_models[[3]] = lmer(
  autdem ~ lrscale + exp + lrscale*exp + age + educ + polint + sex + survey + (1 | country), 
  data = subset(df, legacy == unique(df$legacy)[2])) # Right-Wing
h2_models[[4]] = lmer(
  lrscale ~ autdem2 + exp + autdem2*exp + age + educ + polint + sex + survey + (1 | country), 
  data = subset(df, legacy == unique(df$legacy)[2])) # Right-Wing
```

Model information:
```{r}
varselect = list(
  c("lrscale", "exp1", "lrscale:exp1"),
  c("autdem2", "exp1", "autdem2:exp1"), 
  c("lrscale", "exp1", "lrscale:exp1"),
  c("autdem2", "exp1", "autdem2:exp1")
)

legacies = c("Left-Wing", "Left-Wing", "Right-Wing", "Right-Wing")
dvs = c("Democratic Support", "Left-Right", "Democratic Support", "Left-Right")

modelnames = c("M2b: Left-Wing (N=55,488) \nDV: Democratic Support", 
               "M2b: Left-Wing (N=55,488)\nDV: Left-Right", 
               "M2a: Right-Wing (N=17,877)\nDV: Democratic Support", 
               "M2a: Right-Wing (N=17,877)\nDV: Left-Right")
```

```{r}
ml_summ = function(model){
  model = summary(model)
  out = data.frame(model$coefficients, stringsAsFactors = FALSE)
  out$variable = rownames(out)
  colnames(out) = c("coeff", "se", "df", "tvalue", "pvalue", "variable")
  out$lb = out$coeff - (1.645*out$se); out$ub = out$coeff + (1.645*out$se)
  return(out)
}

results_h2 = list()

for (i in c(1:4)){
  summ = ml_summ(h2_models[[i]])
  summ$legacy = legacies[i]
  summ$dv = dvs[i]
  summ$model = modelnames[i]
  results_h2[[i]] = summ
}

results_h2 = do.call(rbind, results_h2)
```

Bootstrap: 
```{r}
h2_boots = list()
nsim_n = 5000

for (i in c(1:4)){
  boot = confint(h2_models[[i]], parm= varselect[[i]], method = "boot", 
         nsim = nsim_n, seed = 1993, level = 0.9)
  boot = data.frame(boot)
  colnames(boot) = c("lb_boot", "ub_boot")
  boot$variable = rownames(boot)
  boot$model = modelnames[i]
  boot$coeff_boot = (boot$lb_boot + boot$ub_boot) / 2
  h2_boots[[i]] = boot
  save.image("h2.RData")
}

h2_boots = do.call(rbind, h2_boots)
results_h2 = merge(results_h2, h2_boots, by = c("model", "variable"), all = TRUE)
results_h2$lb_boot[is.na(results_h2$lb_boot)] = results_h2$lb[is.na(results_h2$lb_boot)]
results_h2$ub_boot[is.na(results_h2$ub_boot)] = results_h2$ub[is.na(results_h2$ub_boot)]
results_h2$coeff_boot[is.na(results_h2$coeff_boot)] = results_h2$coeff[is.na(results_h2$coeff_boot)]

summary(h2_models[[2]])
```

Summarize output:
```{r}
results_h2 = results_h2[with(results_h2, order(dv, model)),]

results_h2$model = factor(results_h2$model, ordered = TRUE)

library(plyr)
results_h2$variable = revalue(factor(results_h2$variable), c(
  "(Intercept)" = "Intercept", "age" = "Age", "educ" = "Education", 
  "lrscale" = "Independent Var.", "polint" = "Political Interest", 
  "sexMale" = "Sex:Male", "surveyevs2008" = "EVS 2008", "autdem2" = "Independent Var.",
  "surveywvs1994" = "WVS 1994", "surveywvs1999" = "WVS 1999", "surveywvs2005" = "WVS 2005", 
  "exp1" = "Experience", "lrscale:exp1" = "Independent Var.*Experience", 
  "autdem2:exp1" = "Independent Var.*Experience"
  ))

results_h2$var = as.numeric(as.character(revalue(factor(results_h2$variable),
                           c("Intercept" = "1", 
                             "Age" = "2", 
                             "Education" = "3", 
                             "Political Interest" = "4", 
                             "Sex:Male" = "5", 
                             "EVS 2008" = "6", 
                             "WVS 1994" = "7", 
                             "WVS 1999" = "8", 
                             "WVS 2005" = "9",
                             "Independent Var.*Experience" = "10", 
                             "Experience" = "11", 
                             "Independent Var." = "12"
                            ))))

writexl::write_xlsx(results_h2, paste0(tab_dir, "h2_results.xlsx"))

results_h2 = subset(results_h2, variable != "Intercept")
results_h2 = results_h2[order(results_h2$var),]
results_h2$variable = as.character(results_h2$variable)
varnames = unique(results_h2$variable)
```

```{r}
ggplot(data = results_h2, aes(x = coeff_boot, y = var)) + 
  geom_vline(xintercept = 0, color = "grey70", size = 0.25) +
  geom_segment(aes(x = lb_boot, xend = ub_boot, y = var, yend = var)) + 
  geom_point() + 
  scale_color_grey() + 
  scale_y_continuous(breaks = c(2:(length(varnames)+1)), labels = varnames) + 
  theme_minimal() + 
  theme(axis.title = element_blank(), 
        legend.position = "bottom", legend.title = element_blank(),
        panel.grid.minor.y = element_blank(), 
        strip.text = element_text(size = 10, lineheight = 1.5, vjust = 1) 
        ) +
  facet_wrap(model ~ ., dir = "v", ncol = 2)

ggsave(paste0(fig_dir, "test2.png"), width = 10, height = 8)
```

```{r}
results$variable = revalue(factor(results$variable), c(
  "(Intercept)" = "Intercept", "age" = "Age", "educ" = "Education", "lrscale" = "Left-Right", 
  "polint" = "Political Interest", "sexMale" = "Sex:Male", "surveyevs2008" = "EVS 2008", "surveywvs1994" = "WVS 1994", 
  "surveywvs1999" = "WVS 1999", "surveywvs2005" = "WVS 2005", "exp1" = "Experience", 
  "lrscale:exp1" = "Left-Right*Experience"
  ))

results$var = as.numeric(as.character(revalue(factor(results$variable),
                           c("Intercept" = "1", 
                             "Age" = "2", 
                             "Education" = "3", 
                             "Political Interest" = "4", 
                             "Sex:Male" = "5", 
                             "EVS 2008" = "6", 
                             "WVS 1994" = "7", 
                             "WVS 1999" = "8", 
                             "WVS 2005" = "9",
                             "Left-Right*Experience" = "10", 
                             "Experience" = "11", 
                             "Left-Right" = "12"
                            ))))

results$boot_lower = as.numeric(results$boot_lower); results$boot_upper = as.numeric(results$boot_upper)

results$coeff_boot = (results$boot_lower + results$boot_upper) / 2
results$boot_se = abs(results$boot_upper - results$boot_lower) / 5.15
```

```{r}
dist = 0.1

ggplot(data = subset(results, variable != "Intercept"), aes(x = coeff_boot, y = var, color = type)) + 
  geom_vline(xintercept = 0, color = "grey70", size = 0.25) + 
  geom_point(data = subset(results, variable != "Intercept" & type == "Conditional" & var > 9), 
             aes(x = coeff_boot, y = var + dist, color = type),
             size = 0.5) + 
  geom_segment(data = subset(results, variable != "Intercept" & type == "Conditional" & var > 9),   
               aes(x = boot_lower, xend = boot_upper, y = var + dist, yend = var + dist)) + 
  geom_point(data = subset(results, variable != "Intercept" & type == "Conditional" & var < 10), 
             aes(x = coeff_boot, y = var, color = type),
             size = 0.5) + 
  geom_segment(data = subset(results, variable != "Intercept" & type == "Conditional" & var < 10),   
               aes(x = boot_lower, xend = boot_upper, y = var, yend = var)) + 
  geom_point(data = subset(results, variable != "Intercept" & type == "Unconditional"), 
             aes(x = coeff_boot, y = var - dist, color = type),
             size = 0.5) + 
  geom_segment(data = subset(results, variable != "Intercept" & type == "Unconditional"),   
               aes(x = boot_lower, xend = boot_upper, y = var - dist, yend = var - dist)) + 
  scale_y_continuous(breaks = c(2:12), 
                     labels = c("Age", "Education", "Political Interest", "Sex:Male",
                                "EVS 2008", "WVS 1994", "WVS 1999", "WVS 2005",
                                "Left-Right*Experience", "Experience", "Left-Right")) + 
  scale_color_grey() + 
  theme_minimal() + 
  theme(axis.title = element_blank(), 
        legend.position = "bottom", legend.title = element_blank(),
        panel.grid.minor.y = element_blank(), 
        strip.text = element_text(size = 10, lineheight = 1.5, vjust = 1) 
        ) +
  facet_wrap(. ~ name, nrow = 1)

ggsave(paste(fig_dir, "coefplot_h2_2.png"), width = 8, height = 7)
```


```{r}
writexl::write_xlsx(results, paste0(tab_dir, "results_h2.xlsx"))
```

