---
title: "Table 2"
---

Import Libraries:
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(lme4)
library(lmerTest)
library(boot)
library(lm.beta)
library(memisc)
library(plyr)
library(ggplot2)
```

Import Data:
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
source("source_file.R")
df = subset(df, country != "Hungary" & country != "East Germany")

rescale = function(x) {
 x = x - min(x, na.rm = TRUE)
 x = x/ max(x, na.rm = TRUE)}

df$age = rescale(df$age)
df$lrscale = rescale(df$lrscale)
df$educ = rescale(as.numeric(plyr::revalue(factor(df$educ), c(
        "Uncompleted Primary" = "1",
        "Completed Primary" = "2", 
        "Uncompleted Secondary Vocational" = "3",
        "Completed Secondary Vocational" = "4",
        "Uncompleted Secondary Academic" = "5",
        "Completed Secondary Academic" = "6",
        "University without Official Degree" = "7", 
        "University with Official Degree" = "8"
        ))))
df$polint = rescale(df$polint)
```

Functions:
```{r}
# Function to Calculate ICC Country-Random Effects Only
icc0 = function(model) {
 varcorr = data.frame(VarCorr(model)); varcntry = subset(varcorr, grp == "country")
 varresidual = subset(varcorr, grp == "Residual"); icc = (varcntry$vcov) / (varcntry$vcov + varresidual$vcov)
 return(icc)
 }

# Summary Function 
summarize_tab = function(model, modelname) {
 dd.ML = lme4:::devfun2(model,useSc=TRUE,signames=FALSE)
 
 model_summ = data.frame(
  cbind(variable = rownames(model@vcov_beta), coeff = round(model@beta,3), icc = icc0(model)))
 model_summ$coeff = as.numeric(as.character(model_summ$coeff))
 library(sjstats)
 model_summ$SE = se(model)[,2]
 
 model_summ$SE[model_summ$SE == 0] = 0.001
 model_summ = cbind(model_summ, n = nrow(model@frame))
 model_summ$name = modelname
 
 model_summ$lower = model_summ$coeff - (1.645*model_summ$SE)
 model_summ$upper = model_summ$coeff + (1.645*model_summ$SE)
 model_summ$n_country = length(unique(model@frame$country))
 model_summ$name = modelname
 
 writexl::write_xlsx(model_summ, paste0(tab_dir, modelname, ".xlsx"))
 return(model_summ)}
```

Model Estimation
```{r}
nsim = 10000

models = list()
boots = list()

models[[1]] = lmer(autdem ~ lrscale + age + educ + polint + sex + survey + (1 | country), 
                   data = subset(df, legacy == unique(df$legacy)[1])) 
models[[2]] = lmer(autdem ~ lrscale + age + educ + polint + sex + survey + (1 | country), 
                   data = subset(df, legacy == unique(df$legacy)[2])) 
models[[3]] = lmer(autdem ~ lrscale + age + educ + polint + sex + survey + (1 | country), 
                   data = subset(df, legacy == unique(df$legacy)[3])) 

boots[[1]] = confint(models[[1]], parm = c(3:12), method = "boot", nsim = nsim, seed = 1993, level = 0.9) 
save.image("h1.RData")
boots[[2]] = confint(models[[2]], parm = c(3:12), method = "boot", nsim = nsim, seed = 1993, level = 0.9) 
save.image("h1.RData")
boots[[3]] = confint(models[[3]], parm = c(3:11), method = "boot", nsim = nsim, seed = 1993, level = 0.9) 
save.image("h1.RData")


# Hypothesis 1b
m1d_model = lmer(autdem ~ lrscale + legacy + legacy*lrscale + age + educ + polint + sex + survey + 
                (1 + lrscale | country), data = df)
m1d_boot = confint(m1d_model, parm=c(5:18), method = "boot", nsim = 10000, seed = 1993, level = 0.9)
save.image("h1.RData")
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
m1b = summarize_tab(models[[1]], "Model 1b") 
m1a = summarize_tab(models[[2]], "Model 1a")
m1c = summarize_tab(models[[3]], "Model 1c")
m1d = summarize_tab(m1d_model, "Model 1d")

results = do.call(rbind, list(m1a, m1b, m1c, m1d))

bootframe = function(boot, modelname) {
 bframe = data.frame(variable = rownames(data.frame(boot)),
                     boot_lower = data.frame(boot)[,1],
                     boot_upper = data.frame(boot)[,2])
 bframe$name = modelname
 return(bframe)
}

bootframes = rbind(bootframe(boots[[1]], "Model 1b"), 
                   bootframe(boots[[2]], "Model 1a"),
                   bootframe(boots[[3]], "Model 1c"),
                   bootframe(m1d_boot, "Model 1d"))
library(dplyr)
results = data.frame(merge(results, bootframes, by = c("variable", "name"))) %>%
 mutate_if(is.factor, as.character)

results$coeff_boot = (results$boot_lower + results$boot_upper) / 2
results$boot_se = abs(results$boot_upper - results$boot_lower) / 5.15
```

```{r}
library(plyr)
results$variable = revalue(factor(results$variable), c(
  "(Intercept)" = "Intercept", "age" = "Age", "educ" = "Education", "legacyLeft-Wing" = "Legacy: Left-Wing", 
  "legacyRight-Wing" = "Legacy: Right-Wing", "lrscale" = "Left-Right", 
  "lrscale:legacyLeft-Wing" = "Left-Right*Left-Wing", "lrscale:legacyRight-Wing" = "Left-Right*Right-Wing", 
  "polint" = "Political Interest", "sexMale" = "Sex:Male", "surveyevs2008" = "EVS 2008", "surveywvs1994" = "WVS 1994", 
  "surveywvs1999" = "WVS 1999", "surveywvs2005" = "WVS 2005"   
  ))

results$var = as.numeric(as.character(revalue(factor(results$variable),
                           c("Intercept" = "1", 
                             "Age" = "2", 
                             "Education" = "3", 
                             "Political Interest" = "4", 
                             "Sex:Male" = "5", 
                             "EVS 2008" = "6", 
                             "WVS 1994" = "7", 
                             "WVS 1999" = "8", 
                             "WVS 2005" = "9",
                             "Left-Right*Right-Wing" = "10", 
                             "Left-Right*Left-Wing" = "11", 
                             "Legacy: Left-Wing" = "12", 
                             "Legacy: Right-Wing" = "13", 
                             "Left-Right" = "14"
                            ))))
```

```{r}
correlations = readxl::read_xlsx(paste0(tab_dir, "h1_results_correlations.xlsx"))

correlations$variable = revalue(factor(correlations$variable), c(
   "Legacy Left-Wing" = "Legacy: Left-Wing", "Legacy Right-Wing" = "Legacy: Right-Wing", 
   "Left-Right * Left-Wing" = "Left-Right*Left-Wing", "Left-Right * Right-Wing" = "Left-Right*Right-Wing"))

correlations$var = as.numeric(as.character(revalue(factor(correlations$variable),
                           c("Intercept" = "1", 
                             "Age" = "2", 
                             "Education" = "3", 
                             "Political Interest" = "4", 
                             "Sex:Male" = "5", 
                             "EVS 2008" = "6", 
                             "WVS 1994" = "7", 
                             "WVS 1999" = "8", 
                             "WVS 2005" = "9",
                             "Left-Right*Right-Wing" = "10", 
                             "Left-Right*Left-Wing" = "11", 
                             "Legacy: Left-Wing" = "12", 
                             "Legacy: Right-Wing" = "13", 
                             "Left-Right" = "14"
                            ))))
```
```{r}
results = data.frame(rbind(
  cbind(results, type = "Conditional"), 
  cbind(correlations, type = "Unconditional")
))

results$name2 = revalue(factor(results$name), c(
  "Model 1a" = "Model 1a: Right-Wing\nObs = 18,058; Countries = 6", 
  "Model 1b" = "Model 1b: Left-Wing\nObs = 61,135; Countries = 20",
  "Model 1c" = "Model 1c: Democratic\nObs = 33,608; Countries = 12", 
  "Model 1d" = "Model 1d: Pooled\nObs = 112,801; Countries = 38"
))

```


```{r}
dist = 0.1

ggplot(data = subset(results, variable != "Intercept"), aes(x = coeff_boot, y = var, color = type)) + 
  geom_vline(xintercept = 0, color = "grey70", size = 0.25) + 
  geom_point(data = subset(results, variable != "Intercept" & type == "Conditional" & var > 9), 
             aes(x = coeff_boot, y = var + dist, color = type),
             size = 0.5) + 
  geom_segment(data = subset(results, variable != "Intercept" & type == "Conditional" & var > 9),   
               aes(x = (coeff_boot - (1.645*boot_se)), xend = (coeff_boot + (1.645*boot_se)), 
                   y = var + dist, yend = var + dist)) + 
  geom_point(data = subset(results, variable != "Intercept" & type == "Conditional" & var < 10), 
             aes(x = coeff_boot, y = var, color = type),
             size = 0.5) + 
  geom_segment(data = subset(results, variable != "Intercept" & type == "Conditional" & var < 10),   
               aes(x = (coeff_boot - (1.645*boot_se)), xend = (coeff_boot + (1.645*boot_se)), 
                   y = var, yend = var)) + 
  geom_point(data = subset(results, variable != "Intercept" & type == "Unconditional"), 
             aes(x = coeff_boot, y = var - dist, color = type),
             size = 0.5) + 
  geom_segment(data = subset(results, variable != "Intercept" & type == "Unconditional"),   
               aes(x = (coeff_boot - (1.645*boot_se)), xend = (coeff_boot + (1.645*boot_se)), 
                   y = var - dist, yend = var - dist)) + 
  scale_y_continuous(breaks = c(2:14), labels = c(
    "Age", "Education","Political Interest", "Sex:Male", "EVS 2008", "WVS 1994", 
    "WVS 1999", "WVS 2005", "Left-Right*Right-Wing", "Left-Right*Left-Wing", "Legacy: Left-Wing", 
    "Legacy: Right-Wing", "Left-Right")) + 
  scale_color_grey() + 
  theme_minimal() + 
  theme(axis.title = element_blank(), 
        legend.position = "bottom", legend.title = element_blank(),
        panel.grid.minor.y = element_blank(), 
        strip.text = element_text(size = 10, lineheight = 1.5, vjust = 1) 
        ) +
  facet_wrap(. ~ name2, nrow = 1)

ggsave(paste(fig_dir, "coefplot_h1_2.png"), width = 12, height = 7)
```

```{r}
writexl::write_xlsx(results, paste0(tab_dir, "h1_results.xlsx"))
```





