---
title: "B.2. Directional Analyses"
---

Directories:
```{r}
source("source_file.R")
```

Import data:
```{r}
df = read.csv(paste0(data_dir, "wvs-merged.csv"))
df$native = factor(df$native); df$relig = factor(df$relig); df$educ = factor(df$educ); df$gndr = factor(df$gndr); df$exposure_age = factor(df$exposure_age); df$age_cat = factor(df$age_cat)
head(df)
```

```{r}
controls = c("gndr", "educ", "relig", "polint", "native", "gndr + educ + relig + polint + native")

baseformula = list(
 m1_autdem = c("autdem ~ lrscale", "(1 | country)"),
 m1_lrscale = c("lrscale ~ autdem", "(1 | country)"),
 m1d_autdem = c("autdem ~ lrscale + legacy + legacy*lrscale", "(1 + lrscale | country)"),
 m1d_lrscale = c("lrscale ~ autdem + legacy + legacy*autdem", "(1 + autdem | country)"),
 m2_autdem = c("autdem ~ lrscale + exp + lrscale*exp", "(1 | country)"), 
 m2_lrscale = c("lrscale ~ autdem + exp + autdem*exp", "(1 | country)"), 
 m3_autdem = c("autdem ~ lrscale + exposure + exposure*lrscale", "(1 | country)"),
 m3_lrscale = c("lrscale ~ autdem + exposure + exposure*autdem", "(1 | country)"),
 m4_autdem = c("autdem ~ lrscale + exposure_age + exposure_age*lrscale", "(1 | country)"),
 m4_lrscale = c("lrscale ~ autdem + exposure_age + exposure_age*autdem", "(1 | country)")
)
```

Function loop over MLs, adding one control in vector "controls" per analysis
```{r}
direc_analysis = function(data, baseformula_element_i, name) {
 library(lme4)
 library(lmerTest)
 data$country = factor(data$country)
 model_name = names(baseformula[baseformula_element_i])
 baseformula_element = baseformula[[baseformula_element_i]]
 
 for (j in c(1:6)) {
  directory = paste0(robust_dir, "directional-", model_name, name, "_", controls[j], ".txt")
  formula = paste(baseformula_element[1], controls[j], baseformula_element[2], sep = " + ")
  model = lmer(formula, data = data) 
  sink(directory); print(summary(model)); sink() 
 }
}
```

Hypothesis 1
```{r}
for (i in c(1:2)) {direc_analysis(subset(df, legacy == "Right-Wing"), i, "_h1a")}
for (i in c(1:2)) {direc_analysis(subset(df, legacy == "Left-Wing"), i, "_h1b")}
for (i in c(1:2)) {direc_analysis(subset(df, legacy == "Democratic"), i, "_h1c")}
for (i in c(3:4)) {direc_analysis(df, i, "_h1d")}
```

Hypothesis 2
```{r}
for (i in c(5:10)) {direc_analysis(subset(df, legacy == "Left-Wing"), i, "_lw_h2")}
for (i in c(5:10)) {direc_analysis(subset(df, legacy == "Right-Wing"), i, "_rw_h2")}
```


