---
title: "B.4. Prodemocratic versus antidemocratic citizens"
---

```{r}
source("source_file.R")
```

List with models:
```{r}
models_list = list(
 h1 = "autdem ~ lrscale + (1 | country)",
 h2a = "autdem ~ lrscale + exp + age + survey + lrscale*exp + 
 lrscale*age + lrscale*survey + (1 | country)",
 h2b = "autdem ~ lrscale + exposure + lrscale*exposure + age_cat + lrscale*age_cat + 
 survey + lrscale*exposure + lrscale*survey + (1 | country)",
 h2c = "autdem ~ lrscale + exposure_age + lrscale*exposure_age + 
 age + survey + lrscale*age + lrscale*survey + (1 | country)" )
```

Rescale variables in analyses (to avoid non-convergence):
```{r}
rescale = function(x) {x = x - min(x, na.rm = TRUE); x = x/max(x, na.rm = TRUE)} # function to rescale to 0-1 scale
df$lrscale = rescale(df$lrscale); df$age = rescale(df$age); df$exposure = rescale(df$exposure)
```

Subsets for pro and antidemocratic citizens:
```{r}
prodem = subset(df, autdem >= 0); antidem = subset(df, autdem <= 0)
```

Multilevels for prodemocratic citizens:
```{r}
library(lme4)
library(lmerTest)
library(papeR)

proantidem_test = function(data, name) {
 list = list()
 for (i in c(1:4)) {
  model = lmer(models_list[[i]], data = data); model = prettify(summary(model))
  model$legacy = unique(data$legacy)[1]; model$model = paste("Model", i)
  list[[i]] = model}
 list = do.call(rbind, list)
 list$type = name
 return(list)}
```

Estimate and save parameters for different subsets of data:
```{r}
proantidem_df = 
 rbind(proantidem_test(subset(prodem, legacy == "Right-Wing"), "Prodemocratic"),
       proantidem_test(subset(prodem, legacy == "Left-Wing"), "Prodemocratic"),
       proantidem_test(subset(antidem, legacy == "Right-Wing"), "Antidemocratic"),
       proantidem_test(subset(antidem, legacy == "Left-Wing"), "Antidemocratic"))
```

```{r}
colnames(proantidem_df)[1] = "Parameter"
relevant_pars = subset(proantidem_df, Parameter == "lrscale" | Parameter == "lrscale:exp1" | 
                       Parameter == "lrscale:exposure" | Parameter == "lrscale:exposure_age4")
relevant_pars$Num = as.numeric(as.factor(relevant_pars$Parameter))
relevant_pars
```
```{r}
subset(relevant_pars, Parameter == "lrscale:exposure")
```

```{r}
relevant_pars
```


```{r}
relevant_pars$se = relevant_pars$`Std. Error`
vsp = 0.15
width = 0.1

ggplot2::ggplot(data = relevant_pars, aes(x = Num, y = Estimate, fill = type)) + 
 geom_hline(yintercept = 0) +
 geom_rect(data=subset(relevant_pars, type == "Prodemocratic"), alpha=0.5,
           mapping=aes(ymin=Estimate - `Std. Error`, ymax=Estimate + `Std. Error`, 
                       xmin=Num-width+vsp, xmax=Num+width+vsp)) + 
 geom_rect(data=subset(relevant_pars, type == "Antidemocratic"), alpha=0.5,
           mapping=aes(ymin=Estimate - `Std. Error`, ymax=Estimate + `Std. Error`, 
                       xmin=Num-width-vsp, xmax=Num+width-vsp)) + 
 geom_point(data=subset(relevant_pars, type == "Prodemocratic"), mapping=aes(x=Num+vsp, y = Estimate), size = 0.7) +  
 geom_point(data=subset(relevant_pars, type == "Antidemocratic"), mapping=aes(x=Num-vsp, y = Estimate), size = 0.7) +  
 scale_x_continuous(breaks = seq(1,4,1), labels = c("Left-Right", "Left-Right x Experience", 
                                                    "Left-Right x Exposure", "Left-Right x Early Exposure")) + 
 scale_y_continuous(breaks = seq(-1, 1, 0.25), labels = seq(-1, 1, 0.25)) + 
 scale_fill_manual(values = c("black", "grey70")) + 
 theme_minimal() + 
 theme(axis.text.x = element_text(angle = 90, vjust = 0.5), axis.title = element_blank(),
       legend.position = "bottom", legend.title = element_blank(), panel.grid.minor = element_blank()) + 
 coord_flip() + 
 facet_grid(model~legacy) 

ggsave(paste0(fig_dir, "annex_proantidem.png"), width = 8, height = 6)
```

