---
title: "Table 3 - Individual Level Legacy Effects"
---

Import Libraries:
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(lme4)
library(lmerTest)
library(boot)
library(lm.beta)
library(memisc)
library(plyr)
```

Import Data:
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
source("source_file.R")
df = subset(df, country != "Hungary" & country != "East Germany")
df$country = factor(df$country)
```

Rescale left-right:
```{r}
rescale = function(x) {
 x = x - min(x, na.rm = TRUE)
 x = x/ max(x, na.rm = TRUE)}
df$lrscale = rescale(df$lrscale)
```

```{r}
# Function to Calculate ICC Country-Random Effects Only
icc0 = function(model) {
 varcorr = data.frame(VarCorr(model)); varcntry = subset(varcorr, grp == "country")
 varresidual = subset(varcorr, grp == "Residual"); icc = (varcntry$vcov) / (varcntry$vcov + varresidual$vcov)
 return(icc)
}

# Summary Function 
h2_summ = function(model, modelname) {
 dd.ML = lme4:::devfun2(model,useSc=TRUE,signames=FALSE)
 
 model_summ = data.frame(
  cbind(variable = rownames(model@vcov_beta), coeff = round(model@beta,3), icc = icc0(model)))
 model_summ$coeff = as.numeric(as.character(model_summ$coeff))
 library(sjstats)
 model_summ$SE = se(model)[,2]
 
 model_summ$SE[model_summ$SE == 0] = 0.001
 model_summ = cbind(model_summ, n = nrow(model@frame))
 model_summ$name = modelname
 
 model_summ$lower = model_summ$coeff - (1.645*model_summ$SE)
 model_summ$upper = model_summ$coeff + (1.645*model_summ$SE)
 model_summ$n_country = length(unique(model@frame$country))
 model_summ$name = modelname
 
 writexl::write_xlsx(model_summ, paste0(tab_dir, modelname, ".xlsx"))
 return(model_summ)}
```


Hypothesis 2a:
```{r}
h2a_models = list()
h2a_boots = list()

for (i in c(1:2)) {
 sub = subset(df, legacy == unique(df$legacy)[i])
 h2a_models[[i]] = lmer(autdem ~ lrscale + exp + lrscale*exp + survey + age + (1 | country), data=sub)
 h2a_boots[[i]] = confint(h2a_models[[i]], parm = c(3:11), method = "boot", nsim = 10000, seed = 1993, level = 0.9) 
}

h2a_1 = h2_summ(h2a_models[[1]], "M2a: Experience LW")
h2a_2 = h2_summ(h2a_models[[2]], "M2a: Experience RW")

save.image("workspace_h2.RData")
```

Hypothesis 2b:
```{r}
h2b_models = list()
h2b_boots = list()

for (i in c(1:2)) {
 sub = subset(df, legacy == unique(df$legacy)[i])
 sub$exposure = rescale(sub$exposure)
 h2b_models[[i]] = lmer(autdem ~ lrscale + exposure + lrscale*exposure + age_cat + 
                        survey + (1 | country), data=sub)
 h2b_boots[[i]] = confint(h2b_models[[i]], parm = c(3:13), method = "boot", nsim = 10000, seed = 1993, level = 0.9)
}

h2b_1 = h2_summ(h2b_models[[1]], "M2b: Exposure LW")
h2b_2 = h2_summ(h2b_models[[2]], "M2b: Exposure RW")

save.image("workspace_h2.RData")
```

Hypothesis 2c:
```{r}
h2c_models = list()
h2c_boots = list()

for (i in c(1:2)) {
 sub = subset(df, legacy == unique(df$legacy)[i])
 h2c_models[[i]] = lmer(autdem ~ lrscale + exposure_age + lrscale*exposure_age + age + 
                        survey + (1 | country), data=sub)
 h2c_boots[[i]] = confint(h2c_models[[i]], parm = c(3:15), method = "boot", nsim = 10000, seed = 1993, level = 0.9)
}

h2c_1 = h2_summ(h2c_models[[1]], "M2c: Experience Age LW")
h2c_2 = h2_summ(h2c_models[[2]], "M2c: Experience Age RW")

save.image("workspace_h2.RData")
```

```{r}
library(dplyr)
results = data.frame(rbind(h2a_1, h2a_2, h2b_1, h2b_2, h2c_1, h2c_2)) %>%
 mutate_if(is.factor, as.character)


boots = data.frame(rbind(
 cbind(variable = rownames(h2a_boots[[1]]), name = "M2a: Experience LW", h2a_boots[[1]]),
 cbind(variable = rownames(h2a_boots[[2]]), name = "M2a: Experience RW", h2a_boots[[2]]),
 cbind(variable = rownames(h2b_boots[[1]]), name = "M2b: Exposure LW", h2b_boots[[1]]),  
 cbind(variable = rownames(h2b_boots[[2]]), name = "M2b: Exposure RW", h2b_boots[[2]]),  
 cbind(variable = rownames(h2c_boots[[1]]), name = "M2c: Experience Age LW", h2c_boots[[1]]),    
 cbind(variable = rownames(h2c_boots[[2]]), name = "M2c: Experience Age RW", h2c_boots[[2]]))) %>%
 mutate_if(is.factor, as.character)

colnames(boots) = c("variable", "name", "lower_boot", "upper_boot")
 
results = merge(results, boots, by = c("variable", "name"), all = TRUE) 

results$lower_boot = as.numeric(results$lower_boot); results$upper_boot = as.numeric(results$upper_boot); 
results$coeff_boot = (results$lower_boot + results$upper_boot) / 2
results$boot_se = abs(results$upper_boot - results$lower_boot) / 5.15

library(plyr)
results$variable = revalue(factor(results$variable), c(
  "(Intercept)" = "Intercept", "age" = "Age (Continuous)", "age_cat2" = "Age: 25-35",             
  "age_cat3" = "Age: 35-45", "age_cat4" = "Age: 45-50", "exp1" = "Experience: Yes",                 
  "exposure" = "Years of Exposure", "exposure_age2" = "Exp. Age: Adult",
  "exposure_age3" = "Exp. Age: Full", "exposure_age4" = "Exp. Age: Early", 
  "lrscale" = "Left-Right", "lrscale:exp1" = "Left-Right * Experience",      
  "lrscale:exposure" = "Left-Right * Exposure", "lrscale:exposure_age2" = "Left-Right * Adult Exp.",
  "lrscale:exposure_age3" = "Left-Right * Full Exp.", 
  "lrscale:exposure_age4" = "Left-Right * Early Exp.", 
  "surveyevs2008" = "Survey: EVS 2008", 
  "surveywvs1994" = "Survey: WVS 1994", "surveywvs1999" = "Survey: WVS 1999", 
  "surveywvs2005" = "Survey: WVS 2005"))

results$var = as.numeric(as.character(revalue(factor(results$variable), c(
 "Left-Right * Early Exp." = "1", "Left-Right * Full Exp." = "2", "Left-Right * Adult Exp." = "3",
 "Left-Right * Exposure" = "4",  "Left-Right * Experience" = "5", 
 "Survey: WVS 2005" = "6", "Survey: WVS 1999" = "7", "Survey: WVS 1994" = "8", "Survey: EVS 2008" = "9",
 "Age: 45-50" = "10", "Age: 35-45" = "11", "Age: 25-35" = "12",
 "Exp. Age: Early" = "13", "Exp. Age: Full" = "14", "Exp. Age: Adult" = "15",
 "Years of Exposure" = "16", "Experience: Yes" = "17", "Age (Continuous)" = "18",
 "Left-Right" = "19", "Intercept" = "20"
 ))))

save.image("workspace_h2.RData")
```

Density 
```{r}
norms = list()

for (i in c(1:nrow(results))) {
 row = results[i,]
 dist = data.frame(
  boot_lower = row$lower_boot, boot_upper = row$upper_boot,
  variable = row$variable, name = row$name, var = row$var, 
  distrib = rnorm(50000, row$coeff_boot, row$boot_se))
 norms[[i]] = dist
}

norm = do.call(rbind, norms)
save.image("workspace_h2.RData")
```

```{r}
library(forcats)
library(ggplot2)
library(metR)
library(magrittr)
library(grid)
library(ggridges)
library(ggnewscale)
library(ggpubr)
```

```{r}
library(metR)
library(magrittr)
library(grid)
library(ggridges)
library(ggplot2)
library(ggnewscale)
library(ggpubr)

plotggridge = function(model_no, labeltext, plottitle) {
 
 library(forcats)
 norm = norm %>% mutate(variable = fct_reorder(variable, var)) 
 
 ggplot(subset(norm, name == unique(norm$name)[model_no] & variable != "Intercept"|
                     name == unique(norm$name)[model_no + 1] & variable != "Intercept"), 
              aes(distrib, factor(variable), fill = factor(stat(quantile)))) + 
  
    ggtitle(plottitle) + 
 
    geom_vline(xintercept = 0, color = "grey30", alpha = 0.5) +
    
    stat_density_ridges(
     rel_min_height = 0.01,
     data = subset(norm, name == unique(norm$name)[model_no] & variable != "Intercept"), 
     aes(distrib, factor(variable), fill = factor(stat(quantile)), color = name),
     geom = "density_ridges_gradient", 
     calc_ecdf = FALSE, quantiles = c(0.05, 0.95),
     quantile_lines = TRUE, 
     size = 0.25) +
  
    scale_fill_manual(values = c("gray90", "grey30", "gray90"), guide = "none") + 
  
    new_scale("fill") +   
  
    stat_density_ridges(
     rel_min_height = 0.01,
     data = subset(norm, name == unique(norm$name)[model_no + 1] & variable != "Intercept"), 
     aes(distrib, factor(variable), fill = factor(stat(quantile)), color = name),
     
     
     geom = "density_ridges_gradient", 
     calc_ecdf = FALSE, quantiles = c(0.05, 0.95),
     quantile_lines = TRUE, 
     size = 0.25) +
    
    theme_minimal() + 
  
    scale_fill_manual(values = c("gray90", "grey70", "gray90"), guide = "none") +
    scale_color_manual(values = c("grey30", "grey70"),
                       labels = c(labeltext[1],labeltext[2])) + 
    scale_x_continuous(breaks = seq(-0.75, 0.75, 0.25), limits = c(-0.75,0.75)) + 
    
    theme(legend.position = "bottom", 
          legend.title = element_blank(),
          #legend.key.size = unit(1.5, "cm"),
          #legend.key.width = unit(0.25,"cm") ,
          legend.text = element_text(lineheight = 1.5, hjust = 0, vjust = 0.5),
          legend.direction = "vertical",
          axis.title = element_blank(), 
          strip.text.x = element_text(face = "bold", size =  9),
          panel.grid.minor = element_blank(), 
          panel.spacing = unit(2, "lines"), 
          plot.title = element_text(hjust = 0.5)) + 
  guides(color = guide_legend(override.aes = list(size = 5, fill = c("tomato4", "dodgerblue4"))))
}

p1 = plotggridge(1, c("Left-Wing | Observations=61,135 |Countries=20 | ICC=8.56%",
                      "Right-Wing | Observations=18,058 | Countries=6 | ICC=12.71%"), 
                 "Model 2a: Experience")

p2 = plotggridge(3, c("Left-Wing | Observations=61,135 | Countries=20 | ICC=8.71%",
                      "Right-Wing | Observations=18,058 | Countries=6 | ICC=12.63%"), 
                 "Model 2b: Duration of Exposure")

p3 = plotggridge(5, c("Left-Wing | Observations=61,135 | Countries=20 | ICC=8.56%", 
                      "Right-Wing | Observations=18,058 | Countries=6 | ICC=11.93%"),
                 "Model 2c: Age of Exposure")

ggarrange(p1, p2, p3, nrow = 3, heights = c(1, 1.1, 1.2))
ggsave(paste(fig_dir, "coefplot_h2.png"), width = 8, height = 10)
```

```{r}
writexl::write_xlsx(results, paste0(tab_dir, "results_h2.xlsx"))
```

