---
title: "Table 1: Summary Statistics"
---

```{r}
source("source_file.R")
df = subset(df, country!="Hungary" & country != "East Germany")

rescale = function(x) {
 x = x - min(x, na.rm = TRUE)
 x = x/ max(x, na.rm = TRUE)}

df$age = rescale(df$age)
df$lrscale = rescale(df$lrscale)
df$educ = rescale(as.numeric(plyr::revalue(factor(df$educ), c(
        "Uncompleted Primary" = "1",
        "Completed Primary" = "2", 
        "Uncompleted Secondary Vocational" = "3",
        "Completed Secondary Vocational" = "4",
        "Uncompleted Secondary Academic" = "5",
        "Completed Secondary Academic" = "6",
        "University without Official Degree" = "7", 
        "University with Official Degree" = "8"
        ))))
df$polint = rescale(df$polint)
```

```{r}
descriptives = list()

library(psych)

summarizevar = function(var) {
 row = data.frame(n = describe(var)$n, mean = describe(var)$mean, sd = describe(var)$sd, 
                  min = describe(var)$min, max = describe(var)$max)
 return(row)
}

for (i in c(1:5)) {
 vars = list(df$autdem, df$age, df$educ, df$lrscale, df$polint)
 namevar = c("Democratic Support", "Age", "Educational Attainment", "Left-Right", "Political Interest")
 descriptives[[i]] = cbind(summarizevar(vars[[i]]), name = namevar[i])
}

descriptives = do.call(rbind, descriptives)
writexl::write_xlsx(descriptives, paste0(tab_dir, "Table 1 - Continuous.xlsx"))
```

```{r}
desc_cat = list()

summ_cat = function(var) {
 data = data.frame(values = colnames(t(table(var))),
           n = data.frame(t(table(var)))$Freq, 
           proportion = data.frame(t(prop.table(table(var))))$Freq)
 return(data)
}

for (i in c(1:3)) {
 vars = list(df$exp, df$sex, df$survey)
 namevar = c("Experience", "Sex", "Survey-Year")
 desc_cat[[i]] = cbind(summ_cat(vars[[i]]), name = namevar[i])
}

desc_cat = do.call(rbind, desc_cat)

writexl::write_xlsx(desc_cat, paste0(tab_dir, "Table 1 - Categorical.xlsx"))
```


